Repository ursa-labs/ursabot, pull requests merged in 2019-05, with the labels that each got.

#45 Allow docker hostconfig in configuration
  master.cfg
  test.toml
Labels: enhancement

#81 Tune reporters: control report events
  ursabot/formatters.py
  ursabot/hooks.py
  ursabot/reporters.py
  ursabot/tests/test_formatters.py
  ursabot/tests/test_reporters.py
Labels: WIP

#83 Fix build filter in reporters
  prod.toml
  ursabot/reporters.py
  ursabot/tests/test_reporters.py
Labels: bug
